name: parsi
description: "A new Flutter project."

publish_to: 'none'

version: 1.1.2+3

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons:
  provider:
  icons_launcher:
  rename:
  image_picker:
  lottie:
  app_links:
  dart_ping:
  http:
  humanizer:
  gap:
  url_launcher:
  shared_preferences:
  intl:
  auto_size_text:
  neat_periodic_task:
  package_info_plus: any
  percent_indicator:
  cached_network_image:
  flutter_cache_manager:
  gauge_indicator:
  syncfusion_flutter_gauges:
  mobile_device_identifier:
  flutter_v2ray_client_desktop:
    git:
      url: https://github.com/maa1379/desktopVpnSrc.git
      ref: main
  webview_flutter:
  internet_connection_checker_plus:
  video_player:
  chewie:
  async:
  persian_number_utility:
  badges:
#  traffic_stats:
  ffi:
  path_provider:
  path:
  device_info_plus:
  window_manager:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: BHoma
      fonts:
        - asset: assets/fonts/BHoma.ttf



icons_launcher:
  image_path: "assets/images/logo2.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/logo2.png"
    macos:
      enable: true
      image_path: "assets/images/logo2.png"
    windows:
      enable: true
      image_path: "assets/images/logo2.png"
    linux:
      enable: true
      image_path: "assets/images/logo2.png"

